### PR TITLE
Update to new sr

### PR DESCRIPTION
**Pull request by shaddi**
Bumps version, mostly.

### CODE REVIEW

**Comment by yosemitebandit** [comment]
oh snap.

**Comment by yosemitebandit** [comment]
I guess #14 makes this out of date, sorry I never saw this!

**Comment by yosemitebandit** [comment]
hm, though maybe we want this in the changelog..?

**Comment by shaddi** [comment]
You can add it in the #14 changelog, totally forgot about this one. Closing.

**Pull request closed without merging**
